spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: library
    password: library
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka