version: '3.1'

services:

  db:
    image: postgres:9.4
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  discovery-server:
      image: discovery-server
      ports:
        - 8761:8761
      depends_on:
        - db

  library-service:
    image: library-service
    depends_on:
      - discovery-server
    ports:
      - 8081:8081
    environment:
       - "SPRING_PROFILES_ACTIVE=dev"

  notification-service:
    image: notification-service
    depends_on:
      - discovery-server
    ports:
      - 8082:8082
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"